import { defineConfig } from 'tsup'

export default defineConfig({
  entry: ['src/index.ts'],
  format: ['cjs', 'esm'],
  dts: true,
  clean: true,
  splitting: false,
  sourcemap: true,
  external: [
    // Node built-ins
    'process',
    'path',
    'fs',
    'os',
    'util',
    'events',
    'stream',
    'buffer',
    'crypto',
    'url',
    'http',
    'https',
    'net',
    'tls',
    'dns',
    'child_process',
    'cluster',
    'worker_threads',
    'perf_hooks',
    'async_hooks',
    'string_decoder',
    'querystring',
    'zlib',
    // Dependencies that have CJS/ESM issues
    'yaml',
    'js-yaml',
    'pg',
    'lru-cache',
    '@anthropic-ai/sdk',
    '@langchain/anthropic',
    '@langchain/core',
    '@langchain/langgraph',
    'zod',
  ],
  platform: 'node',
  target: 'node20',
  shims: true,
  treeshake: true,
  minify: false,
})
